---
template_variables:
  hide_content: false
  book_title: VMware Tanzu Documentation
  book_title_short: VMware Tanzu Docs
  title: <span class="title-deemph">VMware Tanzu</span> Documentation
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation to help you install, understand, and succeed with VMware's enterprise-grade software."

  tile_name: VMware Tanzu RabbitMQ for VMs
  product_url: https://network.pivotal.io/products/pivotal-cf
  product_link: <div class="header-item"><a href="https://network.pivotal.io/products/VMware Tanzu-cf">Back to Product Page</a></div>

  support_link: <a href="http://tanzu.vmware.com/support" target="_blank">Support</a>
  support_call_to_action: <a href="http://tanzu.vmware.com/support" target="_blank">Need Support?</a>
  support_url: http://tanzu.vmware.com/support

  product_network: VMware Tanzu Network

  path_to_partials: /rabbitmq-cf/partials

  api_version: 235
  gtm_account_id: GTM-MM86KCJ

  use_global_header: true
  global_header_product_href: https://network.pivotal.io/
  global_header_product_link_text: Downloads

  # Tanzu variables

  product_full: VMware Tanzu RabbitMQ for VMs
  product_short: Tanzu RabbitMQ
  product_abbr: Tanzu RabbitMQ

  app_runtime_full: VMware Tanzu Application Service for VMs
  app_runtime_abbr: TAS for VMs

  k8s_runtime_full: Tanzu Kubernetes Grid Integrated Edition
  k8s_runtime_abbr: TKGI

  windows_runtime_full: VMware Tanzu Application Service for VMs &#91;Windows&#93;
  windows_runtime_abbr: TAS for VMs &#91;Windows&#93;

  segment_runtime_full: Isolation Segment

  ops_manager: Ops Manager

  # Pivotal variables

  platform_name: Pivotal Platform
  platform_old: Pivotal Cloud Foundry
  platform_code: PCF
  product_name_lc: pcf

  product_full_pivotal: RabbitMQ for Pivotal Platform
  product_short_pivotal: RabbitMQ for Pivotal Platform
  product_abbr_pivotal: RabbitMQ for Pivotal Platform

  product_old: RabbitMQ for Pivotal Cloud Foundry

  app_runtime_full_pivotal: Pivotal Application Service
  app_runtime_abbr_pivotal: PAS

  k8s_runtime_full_pivotal: Pivotal Container Service

  windows_runtime_full_pivotal: Pivotal Application Service for Windows
  windows_runtime_abbr_pivotal: PASW

  segment_runtime_full_pivotal: Pivotal Isolation Segment

  ops_manager_full: Pivotal Operations Manager

  # Other variables

  service_name: Tanzu RabbitMQ
  service_name_article: the Tanzu RabbitMQ
  service_name_article_full: the VMware Tanzu RabbitMQ for VMs service

  note_pre_provisioned: Previous deprecation warnings for the pre-provisioned service are no longer in effect. VMware continues to support the pre-provisioned service.
